theme = "catppuccin-macchiato"
confirm-before-quit = false
option-as-alt = "left"
padding-x = 10
padding-y = [10, 10]

[editor]
program = "neovim"

[fonts]
size = 14
family = "3270 Nerd Font Mono"

[window]
opacity = 0.85
width = 1200
height = 800

