# theme = "catppuccin-macchiato"
theme = "gruvbox-dark"
confirm-before-quit = false
option-as-alt = "left"
padding-x = 10
padding-y = [10, 10]

[editor]
program = "nvim"

[fonts]
size = 14
family = "3270 Nerd Font Mono"

[navigation]
mode = "Bookmark"

[window]
opacity = 0.65
blur = true
width = 1352
height = 878
decorations = "Buttonless"

[bindings]
keys = [
  { key = "f", with = "super | shift", action = "ToggleFullscreen" },
]
